user_path: "/home/dimitrios/nlp_final"

n_classes: 6000  # n_words
d_model: 384
seq_len : 128
mem_len : 2 * seq_len
batch_size : 4
n_heads : 6
dropout_rate : 0.3
n_layers : 8
n_epochs : 200

lr : 0.00002
max_segs_per_batch : 8

pad_idx : 0
